"""Reference data for categories and governance questions."""

from decimal import Decimal

CATEGORY_SEED = [
    {
        "code": "accountability",
        "name": "Accountability & Governance",
        "weight": Decimal("15.00"),
        "sort_order": 1,
        "description": "Governance structure, ownership, policies, and oversight",
    },
    {
        "code": "human_oversight",
        "name": "Human Oversight",
        "weight": Decimal("15.00"),
        "sort_order": 2,
        "description": "Human involvement, override capability, and decision review",
    },
    {
        "code": "privacy",
        "name": "Privacy & Data Governance",
        "weight": Decimal("15.00"),
        "sort_order": 3,
        "description": "Data collection, retention, access controls, and privacy risks",
    },
    {
        "code": "fairness",
        "name": "Fairness & Non-Discrimination",
        "weight": Decimal("15.00"),
        "sort_order": 4,
        "description": "Bias testing, demographic analysis, and fairness monitoring",
    },
    {
        "code": "transparency",
        "name": "Transparency & Explainability",
        "weight": Decimal("10.00"),
        "sort_order": 5,
        "description": "AI disclosure, documentation, and explainability",
    },
    {
        "code": "security",
        "name": "Security & Robustness",
        "weight": Decimal("10.00"),
        "sort_order": 6,
        "description": "Cybersecurity, input validation, and incident response",
    },
    {
        "code": "risk_management",
        "name": "AI Impact & Risk Management",
        "weight": Decimal("10.00"),
        "sort_order": 7,
        "description": "Impact assessment, harm documentation, and approval processes",
    },
    {
        "code": "lifecycle",
        "name": "Monitoring & Lifecycle Management",
        "weight": Decimal("5.00"),
        "sort_order": 8,
        "description": "Post-deployment monitoring, drift detection, and retirement",
    },
    {
        "code": "affected_people",
        "name": "Accountability to Affected People",
        "weight": Decimal("5.00"),
        "sort_order": 9,
        "description": "Complaints process, challenge rights, and remediation",
    },
]

# Each question: code, text, governance_objective, risk_level, recommendation_key
QUESTION_SEED: dict[str, list[dict[str, str]]] = {
    "accountability": [
        {
            "code": "acc_owner",
            "text": "Is there a clearly identified AI system owner?",
            "governance_objective": "Establish clear ownership and accountability for the AI system.",
            "risk_level": "high",
            "recommendation_key": "acc_owner",
        },
        {
            "code": "acc_responsibilities",
            "text": "Are governance responsibilities assigned for the AI system?",
            "governance_objective": "Assign explicit governance duties across relevant roles.",
            "risk_level": "high",
            "recommendation_key": "acc_responsibilities",
        },
        {
            "code": "acc_policy",
            "text": "Is there an AI governance policy?",
            "governance_objective": "Document organizational expectations for responsible AI use.",
            "risk_level": "high",
            "recommendation_key": "acc_policy",
        },
        {
            "code": "acc_roles_documented",
            "text": "Are roles and responsibilities documented?",
            "governance_objective": "Ensure accountability is visible and operationalized.",
            "risk_level": "medium",
            "recommendation_key": "acc_roles_documented",
        },
        {
            "code": "acc_escalation",
            "text": "Is there an escalation process for AI-related issues?",
            "governance_objective": "Enable timely response to governance concerns.",
            "risk_level": "high",
            "recommendation_key": "acc_escalation",
        },
        {
            "code": "acc_senior_oversight",
            "text": "Is there senior management oversight of the AI system?",
            "governance_objective": "Ensure leadership visibility and accountability.",
            "risk_level": "medium",
            "recommendation_key": "acc_senior_oversight",
        },
        {
            "code": "acc_inventory",
            "text": "Is the AI system included in an AI inventory?",
            "governance_objective": "Maintain organizational visibility of AI systems in use.",
            "risk_level": "medium",
            "recommendation_key": "acc_inventory",
        },
    ],
    "human_oversight": [
        {
            "code": "ho_human_involved",
            "text": "Is a human involved in consequential decisions?",
            "governance_objective": "Ensure meaningful human involvement in high-impact decisions.",
            "risk_level": "critical",
            "recommendation_key": "ho_human_involved",
        },
        {
            "code": "ho_override",
            "text": "Can humans override AI recommendations?",
            "governance_objective": "Preserve human authority over AI-assisted outcomes.",
            "risk_level": "critical",
            "recommendation_key": "ho_override",
        },
        {
            "code": "ho_escalation",
            "text": "Are escalation procedures defined for AI-assisted decisions?",
            "governance_objective": "Provide a path for uncertain or disputed outcomes.",
            "risk_level": "high",
            "recommendation_key": "ho_escalation",
        },
        {
            "code": "ho_training",
            "text": "Are reviewers trained to oversee AI-assisted decisions?",
            "governance_objective": "Build competent human oversight capacity.",
            "risk_level": "high",
            "recommendation_key": "ho_training",
        },
        {
            "code": "ho_automation_bias",
            "text": "Is automation bias considered in oversight procedures?",
            "governance_objective": "Mitigate over-reliance on AI recommendations.",
            "risk_level": "medium",
            "recommendation_key": "ho_automation_bias",
        },
        {
            "code": "ho_documentation",
            "text": "Are human decisions and overrides documented?",
            "governance_objective": "Maintain an audit trail of human judgment.",
            "risk_level": "medium",
            "recommendation_key": "ho_documentation",
        },
        {
            "code": "ho_challenge",
            "text": "Is there a process for challenging AI-assisted decisions?",
            "governance_objective": "Enable review and correction of AI-influenced outcomes.",
            "risk_level": "high",
            "recommendation_key": "ho_challenge",
        },
    ],
    "privacy": [
        {
            "code": "priv_personal_info",
            "text": "Is personal information processed by the system documented?",
            "governance_objective": "Maintain visibility of personal data use.",
            "risk_level": "high",
            "recommendation_key": "priv_personal_info",
        },
        {
            "code": "priv_proportionate",
            "text": "Is data collection necessary and proportionate?",
            "governance_objective": "Limit data use to what is required for the stated purpose.",
            "risk_level": "high",
            "recommendation_key": "priv_proportionate",
        },
        {
            "code": "priv_purpose",
            "text": "Is the purpose of data collection documented?",
            "governance_objective": "Ensure data use aligns with defined purposes.",
            "risk_level": "medium",
            "recommendation_key": "priv_purpose",
        },
        {
            "code": "priv_retention",
            "text": "Are data retention periods defined?",
            "governance_objective": "Prevent unnecessary retention of personal data.",
            "risk_level": "medium",
            "recommendation_key": "priv_retention",
        },
        {
            "code": "priv_access_controls",
            "text": "Are access controls implemented for data used by the AI system?",
            "governance_objective": "Restrict data access to authorized personnel.",
            "risk_level": "high",
            "recommendation_key": "priv_access_controls",
        },
        {
            "code": "priv_data_quality",
            "text": "Is data quality monitored for AI inputs?",
            "governance_objective": "Ensure reliable inputs for AI processing.",
            "risk_level": "medium",
            "recommendation_key": "priv_data_quality",
        },
        {
            "code": "priv_sources",
            "text": "Are data sources documented?",
            "governance_objective": "Enable traceability and accountability for training and operational data.",
            "risk_level": "medium",
            "recommendation_key": "priv_sources",
        },
        {
            "code": "priv_risk_assessment",
            "text": "Are privacy risks assessed for the AI system?",
            "governance_objective": "Identify and address privacy-related harms.",
            "risk_level": "high",
            "recommendation_key": "priv_risk_assessment",
        },
        {
            "code": "priv_processors",
            "text": "Are third-party data processors identified and governed?",
            "governance_objective": "Extend governance to vendor and partner data handling.",
            "risk_level": "high",
            "recommendation_key": "priv_processors",
        },
    ],
    "fairness": [
        {
            "code": "fair_bias_testing",
            "text": "Has the system been tested for bias?",
            "governance_objective": "Detect discriminatory or unfair outcomes before deployment.",
            "risk_level": "critical",
            "recommendation_key": "fair_bias_testing",
        },
        {
            "code": "fair_demographics",
            "text": "Are relevant demographic groups identified for fairness analysis?",
            "governance_objective": "Ensure testing covers populations that may be affected.",
            "risk_level": "high",
            "recommendation_key": "fair_demographics",
        },
        {
            "code": "fair_performance",
            "text": "Are performance differences measured across relevant groups?",
            "governance_objective": "Detect disparate impact across populations.",
            "risk_level": "high",
            "recommendation_key": "fair_performance",
        },
        {
            "code": "fair_vulnerable",
            "text": "Are protected or vulnerable populations considered?",
            "governance_objective": "Apply heightened scrutiny where harm risk is elevated.",
            "risk_level": "high",
            "recommendation_key": "fair_vulnerable",
        },
        {
            "code": "fair_remediation",
            "text": "Is there a process for addressing identified bias?",
            "governance_objective": "Correct unfair outcomes when detected.",
            "risk_level": "high",
            "recommendation_key": "fair_remediation",
        },
        {
            "code": "fair_monitoring",
            "text": "Is fairness monitored after deployment?",
            "governance_objective": "Detect drift or emerging bias in production.",
            "risk_level": "medium",
            "recommendation_key": "fair_monitoring",
        },
        {
            "code": "fair_training_limits",
            "text": "Are training data limitations documented?",
            "governance_objective": "Make known constraints visible to decision-makers.",
            "risk_level": "medium",
            "recommendation_key": "fair_training_limits",
        },
    ],
    "transparency": [
        {
            "code": "trans_disclosure",
            "text": "Are users informed when AI is being used?",
            "governance_objective": "Provide appropriate notice of AI involvement.",
            "risk_level": "high",
            "recommendation_key": "trans_disclosure",
        },
        {
            "code": "trans_purpose",
            "text": "Is the purpose of the AI system documented?",
            "governance_objective": "Clarify why the system exists and what it is intended to do.",
            "risk_level": "medium",
            "recommendation_key": "trans_purpose",
        },
        {
            "code": "trans_role",
            "text": "Can users understand the role AI plays in decisions?",
            "governance_objective": "Support informed understanding of AI influence.",
            "risk_level": "high",
            "recommendation_key": "trans_role",
        },
        {
            "code": "trans_model_docs",
            "text": "Is model documentation available?",
            "governance_objective": "Document system design, data, and intended use.",
            "risk_level": "medium",
            "recommendation_key": "trans_model_docs",
        },
        {
            "code": "trans_limitations",
            "text": "Are system limitations documented?",
            "governance_objective": "Make known constraints visible to users and reviewers.",
            "risk_level": "medium",
            "recommendation_key": "trans_limitations",
        },
        {
            "code": "trans_explanations",
            "text": "Are explanations available when appropriate?",
            "governance_objective": "Support accountability through understandable outputs.",
            "risk_level": "medium",
            "recommendation_key": "trans_explanations",
        },
        {
            "code": "trans_information_requests",
            "text": "Can affected individuals request additional information about AI use?",
            "governance_objective": "Enable transparency for people impacted by the system.",
            "risk_level": "medium",
            "recommendation_key": "trans_information_requests",
        },
    ],
    "security": [
        {
            "code": "sec_cyber_risks",
            "text": "Are cybersecurity risks assessed for the AI system?",
            "governance_objective": "Identify threats to confidentiality, integrity, and availability.",
            "risk_level": "high",
            "recommendation_key": "sec_cyber_risks",
        },
        {
            "code": "sec_access_controls",
            "text": "Are access controls implemented for the AI system?",
            "governance_objective": "Restrict system access to authorized users and services.",
            "risk_level": "high",
            "recommendation_key": "sec_access_controls",
        },
        {
            "code": "sec_misuse_testing",
            "text": "Is the AI system tested against misuse?",
            "governance_objective": "Anticipate adversarial or unintended uses.",
            "risk_level": "high",
            "recommendation_key": "sec_misuse_testing",
        },
        {
            "code": "sec_input_validation",
            "text": "Are model inputs validated?",
            "governance_objective": "Prevent malformed or malicious inputs from affecting outputs.",
            "risk_level": "medium",
            "recommendation_key": "sec_input_validation",
        },
        {
            "code": "sec_output_monitoring",
            "text": "Is model output monitored?",
            "governance_objective": "Detect anomalous or harmful outputs in operation.",
            "risk_level": "medium",
            "recommendation_key": "sec_output_monitoring",
        },
        {
            "code": "sec_incidents_documented",
            "text": "Are security incidents documented?",
            "governance_objective": "Maintain records for analysis and improvement.",
            "risk_level": "medium",
            "recommendation_key": "sec_incidents_documented",
        },
        {
            "code": "sec_incident_response",
            "text": "Is there a process for responding to AI-related security incidents?",
            "governance_objective": "Enable timely containment and remediation.",
            "risk_level": "high",
            "recommendation_key": "sec_incident_response",
        },
        {
            "code": "sec_reliability",
            "text": "Is the system tested for reliability?",
            "governance_objective": "Ensure consistent performance under expected conditions.",
            "risk_level": "medium",
            "recommendation_key": "sec_reliability",
        },
    ],
    "risk_management": [
        {
            "code": "rm_impact_assessment",
            "text": "Has an AI impact assessment been completed?",
            "governance_objective": "Evaluate potential effects before deployment.",
            "risk_level": "critical",
            "recommendation_key": "rm_impact_assessment",
        },
        {
            "code": "rm_stakeholders",
            "text": "Are affected stakeholders identified?",
            "governance_objective": "Understand who may be impacted by the system.",
            "risk_level": "high",
            "recommendation_key": "rm_stakeholders",
        },
        {
            "code": "rm_harms",
            "text": "Are potential harms documented?",
            "governance_objective": "Make foreseeable risks visible and manageable.",
            "risk_level": "high",
            "recommendation_key": "rm_harms",
        },
        {
            "code": "rm_severity",
            "text": "Is the severity of potential harm assessed?",
            "governance_objective": "Prioritize mitigation based on impact magnitude.",
            "risk_level": "high",
            "recommendation_key": "rm_severity",
        },
        {
            "code": "rm_likelihood",
            "text": "Is the likelihood of potential harm assessed?",
            "governance_objective": "Prioritize mitigation based on probability.",
            "risk_level": "high",
            "recommendation_key": "rm_likelihood",
        },
        {
            "code": "rm_mitigation",
            "text": "Are mitigation measures documented?",
            "governance_objective": "Define controls to reduce identified risks.",
            "risk_level": "high",
            "recommendation_key": "rm_mitigation",
        },
        {
            "code": "rm_residual",
            "text": "Are residual risks reviewed?",
            "governance_objective": "Ensure remaining risk is understood and accepted appropriately.",
            "risk_level": "medium",
            "recommendation_key": "rm_residual",
        },
        {
            "code": "rm_approval",
            "text": "Is there a formal approval process before deployment?",
            "governance_objective": "Require explicit authorization for consequential use.",
            "risk_level": "critical",
            "recommendation_key": "rm_approval",
        },
    ],
    "lifecycle": [
        {
            "code": "lc_monitoring",
            "text": "Is the AI system monitored after deployment?",
            "governance_objective": "Detect performance or behavior changes in production.",
            "risk_level": "high",
            "recommendation_key": "lc_monitoring",
        },
        {
            "code": "lc_metrics",
            "text": "Are performance metrics tracked?",
            "governance_objective": "Measure ongoing system effectiveness.",
            "risk_level": "medium",
            "recommendation_key": "lc_metrics",
        },
        {
            "code": "lc_drift",
            "text": "Is model drift monitored?",
            "governance_objective": "Detect changes in data or model behavior over time.",
            "risk_level": "medium",
            "recommendation_key": "lc_drift",
        },
        {
            "code": "lc_incidents",
            "text": "Are incidents tracked?",
            "governance_objective": "Maintain visibility of operational issues.",
            "risk_level": "medium",
            "recommendation_key": "lc_incidents",
        },
        {
            "code": "lc_reviews",
            "text": "Are periodic reviews scheduled?",
            "governance_objective": "Ensure ongoing governance attention.",
            "risk_level": "medium",
            "recommendation_key": "lc_reviews",
        },
        {
            "code": "lc_updates",
            "text": "Is there a process for updating the system?",
            "governance_objective": "Manage changes in a controlled manner.",
            "risk_level": "medium",
            "recommendation_key": "lc_updates",
        },
        {
            "code": "lc_retirement",
            "text": "Is there a process for retiring the AI system?",
            "governance_objective": "Plan for safe decommissioning.",
            "risk_level": "low",
            "recommendation_key": "lc_retirement",
        },
        {
            "code": "lc_change_docs",
            "text": "Are changes to the AI system documented?",
            "governance_objective": "Maintain traceability of system evolution.",
            "risk_level": "medium",
            "recommendation_key": "lc_change_docs",
        },
    ],
    "affected_people": [
        {
            "code": "ap_challenge",
            "text": "Can people challenge AI-assisted decisions?",
            "governance_objective": "Provide a meaningful path to contest outcomes.",
            "risk_level": "critical",
            "recommendation_key": "ap_challenge",
        },
        {
            "code": "ap_complaints",
            "text": "Is there a complaints process for AI-related concerns?",
            "governance_objective": "Enable affected people to raise issues.",
            "risk_level": "high",
            "recommendation_key": "ap_complaints",
        },
        {
            "code": "ap_human_review",
            "text": "Can decisions be reviewed by humans upon request?",
            "governance_objective": "Ensure recourse to human judgment.",
            "risk_level": "critical",
            "recommendation_key": "ap_human_review",
        },
        {
            "code": "ap_informed",
            "text": "Are users informed about relevant AI use?",
            "governance_objective": "Support informed engagement with AI-assisted services.",
            "risk_level": "medium",
            "recommendation_key": "ap_informed",
        },
        {
            "code": "ap_adverse_impacts",
            "text": "Are adverse impacts documented?",
            "governance_objective": "Track harm experienced by affected people.",
            "risk_level": "high",
            "recommendation_key": "ap_adverse_impacts",
        },
        {
            "code": "ap_remediation",
            "text": "Are remediation procedures available?",
            "governance_objective": "Correct harm when it occurs.",
            "risk_level": "high",
            "recommendation_key": "ap_remediation",
        },
    ],
}
